baseURL: /
languageCode: en-us
paginate: 12
menu:
  main:
    - Identifier: articles
      Name: Articles
      URL: /articles/
      Weight: '10'

    - Identifier: design
      Name: Design
      URL: /categories/design/
      Weight: '110'
      parent: "articles"

    - Identifier: development
      Name: Development
      URL: /categories/development/
      Weight: '120'
      parent: "articles"

    - Identifier: gaming
      Name: Gaming
      URL: /categories/gaming/
      Weight: '130'
      parent: "articles"

    - Identifier: nba
      Name: NBA
      URL: /categories/nba/
      Weight: '140'
      parent: "articles"

    - Identifier: about
      Name: About
      URL: /about/
      Weight: '20'

    - Identifier: work
      Name: Work
      URL: /work/
      Weight: '30'

    - Identifier: contact
      Name: Contact
      URL: /contact/
      Weight: '40'
    
taxonomies:
  category: categories
  tag: tags
title: Glenn McComb - Freelance designer and front end developer based in Melbourne, Australia
disableFastRender: true
disqusShortname: "glennmccomb-com"

# Related.
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: categories
      weight: 130
      includeNewer: true