baseURL: /
languageCode: en-us
paginate: 12
menu:
  main:
    # - Identifier: home
    #   Name: Home
    #   URL: /
    #   Weight: '10'

    - Identifier: articles
      Name: Articles
      URL: /articles/
      Weight: '10'

    # - Identifier: design
    #   Name: Design
    #   URL: /categories/design/
    #   Weight: '200'
    #   parent: "articles"

    - Identifier: development
      Name: Development
      URL: /categories/development/
      Weight: '110'
      parent: "articles"

    - Identifier: gaming
      Name: Gaming
      URL: /categories/gaming/
      Weight: '120'
      parent: "articles"

    - Identifier: nba
      Name: NBA
      URL: /categories/nba/
      Weight: '130'
      parent: "articles"

    # - Identifier: about
    #   Name: About
    #   URL: /about/
    #   Weight: '20'

    - Identifier: contact
      Name: Contact
      URL: /contact/
      Weight: '30'

    # - Identifier: projects
    #   Name: Projects
    #   URL: /projects/
    #   Weight: '20'
    
taxonomies:
  category: categories
  tag: tags
title: Glenn McComb - Freelance designer and front end developer based in Melbourne, Australia
disableFastRender: true
disqusShortname: "glennmccomb-com"