baseURL: /
languageCode: en-us
menu:
  main:
    - Identifier: home
      Name: Home
      Pre: ''
      URL: /
      Weight: 1
    - Identifier: articles
      Name: Articles
      Pre: ''
      URL: /articles/
      Weight: 0
menu.main:
  - Identifier: work
    Name: Work
    URL: /work/
    Weight: '0'
title: Hugo Netlify CMS test
