baseURL: /
languageCode: en-us
paginate: 12
menu:
  main:
    # - Identifier: home
    #   Name: Home
    #   URL: /
    #   Weight: '10'

    - Identifier: contact
      Name: Contact
      URL: /contact/
      Weight: '30'

    - Identifier: articles
      Name: Articles
      URL: /articles/
      Weight: '10'

    # - Identifier: design
    #   Name: Design
    #   URL: /categories/design/
    #   Weight: '200'
    #   parent: "articles"

    - Identifier: development
      Name: Development
      URL: /categories/development/
      Weight: '210'
      parent: "articles"

    - Identifier: gaming
      Name: Gaming
      URL: /categories/gaming/
      Weight: '220'
      parent: "articles"

    - Identifier: nba
      Name: NBA
      URL: /categories/nba/
      Weight: '230'
      parent: "articles"

    # - Identifier: projects
    #   Name: Projects
    #   URL: /projects/
    #   Weight: '20'
    
taxonomies:
  category: categories
  tag: tags
title: Glenn McComb - Designer and Front End Developer
disableFastRender: true
disqusShortname: "glennmccomb-com"