languageCode: "en-us"
title: "Hugo Netlify CMS test"
baseURL: "/" # Local base url.
# baseURL: "/hugo-test/" # GitHub base url (repo name).
# publishDir: "docs" # For publishing on GitHub pages (defauly is public/)