baseURL: /
languageCode: en-us
paginate: 3
menu:
  main:
    - Identifier: articles
      Name: Articles
      URL: /articles/
      Weight: '20'
    - Identifier: home
      Name: Home
      URL: /
      Weight: '10'
    - Identifier: work
      Name: Work
      URL: /work/
      Weight: '30'
taxonomies:
  category: categories
  tag: tags
title: Glenn McComb - Designer and Front End Developer
