languageCode: "en-us"
title: "Hugo Netlify CMS test"
baseURL: "/"
menu:
  main:
    - Name: "Home"
      Weight: 0
      Identifier: "home"
      URL: "/"

    - Name: "Articles"
      Weight: 1
      Identifier: "articles"
      URL: "/articles/"