baseURL: /
languageCode: en-us
menu:
  main:
    - Identifier: articles
      Name: Articles
      URL: /articles/
      Weight: 1
    - Identifier: home
      Name: Home
      URL: /
      Weight: 0
    - Identifier: work
      Name: Work
      URL: /work/
      Weight: 2
taxonomies:
  category: categories
  tag: "tags"
title: Glenn McComb - Designer and Front End Developer
