baseURL: /
languageCode: en-us
menu:
  main:
    - Identifier: home
      Name: Home
      URL: /
      Weight: '0'
    - Identifier: articles
      Name: Articles
      URL: /articles/
      Weight: 1
title: Hugo Netlify CMS test
