backend:
  name: github
  repo: lenymo/hugo-test # Path to your Github repository
  branch: master # Branch to update
  
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "articles" # Used in routes, e.g. /admin/collections/articles
    label: "Articles" # Used in the UI
    folder: "content/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "articles"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish date", name: "date", widget: "datetime"}
      - {label: "Featured image", name: "featured", widget: "image", required: false}
      - {label: "SEO description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Custom CSS class", name: "custom_class", widget: "string", required: false}
      - {label: "Transparent site header", name: "transparent_header", widget: "boolean", required: false}
      - {label: "Featured image opacity", name: "featured_opacity", widget: "number", required: false}
      - {label: "Page header dark background", name: "dark_bg", widget: "boolean", required: false}
      - {label: "Page header background color", name: "page_header_bg_color", widget: "string", required: false}
      # - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
  - name: 'contact'
    label: 'Contact'
    folder: 'content/contact'
    create: false
    fields:
      - {label: "Featured image", name: "featured", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Custom CSS class", name: "custom_class", widget: "string", required: false}
      - {label: "Transparent site header", name: "transparent_header", widget: "boolean", required: false}
      - {label: "Featured image opacity", name: "featured_opacity", widget: "number", required: false}
      - {label: "Page header dark background", name: "dark_bg", widget: "boolean", required: false}
      - {label: "Page header background color", name: "page_header_bg_color", widget: "string", required: false}
  - name: "settings"
    label: "Settings"
    files:
      - name: "site-settings"
        label: "Site Settings"
        file: "data/site_settings.yml"
        description: "General site settings"
        fields:
          - {label: "Settings test", name: "settings_test", widget: "string"}

      - name: "social-links"
        label: "Social Links"
        file: "data/social_links.yml"
        description: "Links to my social media profiles"
        fields:
          - {label: "Social Links", name: "social_links", widget: "list", fields: [{label: Name, name: name, widget: string}, {label: Identifier, name: identifier, widget: string}, {label: URL, name: url, widget: string}, {label: Icon, name: icon, widget: string}]}
      
      - name: "menu" # Add menu items here.
        label: "Menu"
        file: "config.yml"
        description: "Main menu in site header"
        fields:
          - {label: "Menu", name: "menu", widget: "object", fields: [{label: "Main menu", name: "main", widget: "list", fields: [{label: "Name", name: "Name", widget: "string"}, {label: "Weight", name: "Weight", widget: "string"}, {label: "Identifier", name: "Identifier", widget: "string"}, {label: "URL", name: "URL", widget: "string"}]}]}