backend:
  name: github
  repo: lenymo/hugo-test # Path to your Github repository
  branch: master # Branch to update
  
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "articles" # Used in routes, e.g. /admin/collections/articles
    label: "Articles" # Used in the UI
    folder: "content/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "articles"}
      - {label: "Title", name: "title", widget: "string"}
      # - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime", default: "{{year}}-{{month}}-{{day}}"}
      - {label: "SEO Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}